<a href="https://colab.research.google.com/github/Mayu-infinite/Practice/blob/main/B23ES1026_Lab1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

np.random.seed(0)
A = np.random.randint(1, 100000, (3, 3))
B = np.random.randint(100000, 200000, (3, 3))

start_time = time.time()
result_np = np.dot(A,B)
end_time = time.time()
numpy_time = end_time - start_time

print("A:\n", A)
print("B:\n", B)
print("Product:\n", result_np)
print("Time taken (NumPy):", numpy_time)


A:
 [[68269 43568 42614]
 [45892 21244 95940]
 [97640 41994 86294]]
B:
 [[155026 180471 180966]
 [148600 139512 152620]
 [180186 117089 132230]]
Product:
 [[24736120998 23388464161 24638565234]
 [27558356432 22479486720 24233297152]
 [36926017724 33583933534 35489300140]]
Time taken (NumPy): 0.000110626220703125


In [ ]:
def matrix_multiplication_loop(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    result = np.zeros((rows_A, cols_B))

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i, j] += A[i, k] * B[k, j] #loop
    return result

start_time = time.time()
result_loop = matrix_multiplication_loop(A, B)
end_time = time.time()
loop_time = end_time - start_time

print("Product:\n", result_loop)
print("Time taken (Loop):", loop_time)


Product:
 [[2.47361210e+10 2.33884642e+10 2.46385652e+10]
 [2.75583564e+10 2.24794867e+10 2.42332972e+10]
 [3.69260177e+10 3.35839335e+10 3.54893001e+10]]
Time taken (Loop): 0.0001690387725830078


Here we saw that the loop takes much more time as compared to the NumPy array multiplication.


In [ ]:
def normalize_matrix(matrix):
    min_val = matrix.min()
    max_val = matrix.max()
    normalized = (matrix - min_val) / (max_val - min_val)
    return normalized

# Normalize
normalized_np = normalize_matrix(result_np)

print(normalized_np)


[[0.15620596 0.06292012 0.14945308]
 [0.35156327 0.         0.12140011]
 [1.         0.76865836 0.9005493 ]]


In [ ]:
import numpy as np

def generate_matrix_and_sum_diagonals(n):

    matrix = np.random.randint(1, 11, (n, n))

    def sum_diagonals(matrix):
        diagonals_sum = []
        for d in range(-n + 1, n):
            diagonal_sum = np.sum(np.diagonal(matrix, offset=d))
            diagonals_sum.append(diagonal_sum)
        return diagonals_sum

    diagonal_sums = sum_diagonals(matrix)
    return matrix, diagonal_sums
n = 5
matrix, diagonal_sums = generate_matrix_and_sum_diagonals(n)
print(matrix)
print(diagonal_sums)



[[8 8 9 2 6]
 [9 5 4 1 4]
 [6 1 3 4 9]
 [2 4 4 4 8]
 [1 2 1 5 8]]
[1, 4, 11, 19, 28, 24, 19, 6, 6]
